// ==============================================================
// Generated by Vitis HLS v2023.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module stream2mem_AXIvideo2xfMat_24_16_1080_1920_1_2_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        vstream_TDATA,
        vstream_TVALID,
        vstream_TREADY,
        vstream_TKEEP,
        vstream_TSTRB,
        vstream_TUSER,
        vstream_TLAST,
        vstream_TID,
        vstream_TDEST,
        img_data_din,
        img_data_num_data_valid,
        img_data_fifo_cap,
        img_data_full_n,
        img_data_write,
        img_rows_c_din,
        img_rows_c_num_data_valid,
        img_rows_c_fifo_cap,
        img_rows_c_full_n,
        img_rows_c_write,
        img_cols_c_din,
        img_cols_c_num_data_valid,
        img_cols_c_fifo_cap,
        img_cols_c_full_n,
        img_cols_c_write
);

parameter    ap_ST_fsm_state1 = 10'd1;
parameter    ap_ST_fsm_state2 = 10'd2;
parameter    ap_ST_fsm_state3 = 10'd4;
parameter    ap_ST_fsm_state4 = 10'd8;
parameter    ap_ST_fsm_state5 = 10'd16;
parameter    ap_ST_fsm_state6 = 10'd32;
parameter    ap_ST_fsm_state7 = 10'd64;
parameter    ap_ST_fsm_state8 = 10'd128;
parameter    ap_ST_fsm_state9 = 10'd256;
parameter    ap_ST_fsm_state10 = 10'd512;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [23:0] vstream_TDATA;
input   vstream_TVALID;
output   vstream_TREADY;
input  [2:0] vstream_TKEEP;
input  [2:0] vstream_TSTRB;
input  [0:0] vstream_TUSER;
input  [0:0] vstream_TLAST;
input  [0:0] vstream_TID;
input  [0:0] vstream_TDEST;
output  [23:0] img_data_din;
input  [1:0] img_data_num_data_valid;
input  [1:0] img_data_fifo_cap;
input   img_data_full_n;
output   img_data_write;
output  [10:0] img_rows_c_din;
input  [1:0] img_rows_c_num_data_valid;
input  [1:0] img_rows_c_fifo_cap;
input   img_rows_c_full_n;
output   img_rows_c_write;
output  [7:0] img_cols_c_din;
input  [1:0] img_cols_c_num_data_valid;
input  [1:0] img_cols_c_fifo_cap;
input   img_cols_c_full_n;
output   img_cols_c_write;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg img_data_write;
reg img_rows_c_write;
reg img_cols_c_write;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [9:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    img_rows_c_blk_n;
reg    img_cols_c_blk_n;
wire    grp_AXIvideo2xfMat_24_16_1080_1920_1_2_Pipeline_loop_start_hunt_fu_148_ap_start;
wire    grp_AXIvideo2xfMat_24_16_1080_1920_1_2_Pipeline_loop_start_hunt_fu_148_ap_done;
wire    grp_AXIvideo2xfMat_24_16_1080_1920_1_2_Pipeline_loop_start_hunt_fu_148_ap_idle;
wire    grp_AXIvideo2xfMat_24_16_1080_1920_1_2_Pipeline_loop_start_hunt_fu_148_ap_ready;
wire    grp_AXIvideo2xfMat_24_16_1080_1920_1_2_Pipeline_loop_start_hunt_fu_148_vstream_TREADY;
wire   [0:0] grp_AXIvideo2xfMat_24_16_1080_1920_1_2_Pipeline_loop_start_hunt_fu_148_axi_last_out;
wire    grp_AXIvideo2xfMat_24_16_1080_1920_1_2_Pipeline_loop_start_hunt_fu_148_axi_last_out_ap_vld;
wire   [23:0] grp_AXIvideo2xfMat_24_16_1080_1920_1_2_Pipeline_loop_start_hunt_fu_148_axi_data_out;
wire    grp_AXIvideo2xfMat_24_16_1080_1920_1_2_Pipeline_loop_start_hunt_fu_148_axi_data_out_ap_vld;
wire    grp_AXIvideo2xfMat_24_16_1080_1920_1_2_Pipeline_loop_col_zxi2mat_fu_168_ap_start;
wire    grp_AXIvideo2xfMat_24_16_1080_1920_1_2_Pipeline_loop_col_zxi2mat_fu_168_ap_done;
wire    grp_AXIvideo2xfMat_24_16_1080_1920_1_2_Pipeline_loop_col_zxi2mat_fu_168_ap_idle;
wire    grp_AXIvideo2xfMat_24_16_1080_1920_1_2_Pipeline_loop_col_zxi2mat_fu_168_ap_ready;
wire   [23:0] grp_AXIvideo2xfMat_24_16_1080_1920_1_2_Pipeline_loop_col_zxi2mat_fu_168_img_data_din;
wire    grp_AXIvideo2xfMat_24_16_1080_1920_1_2_Pipeline_loop_col_zxi2mat_fu_168_img_data_write;
wire    grp_AXIvideo2xfMat_24_16_1080_1920_1_2_Pipeline_loop_col_zxi2mat_fu_168_vstream_TREADY;
wire   [0:0] grp_AXIvideo2xfMat_24_16_1080_1920_1_2_Pipeline_loop_col_zxi2mat_fu_168_last_out;
wire    grp_AXIvideo2xfMat_24_16_1080_1920_1_2_Pipeline_loop_col_zxi2mat_fu_168_last_out_ap_vld;
wire   [23:0] grp_AXIvideo2xfMat_24_16_1080_1920_1_2_Pipeline_loop_col_zxi2mat_fu_168_axi_data_5_out;
wire    grp_AXIvideo2xfMat_24_16_1080_1920_1_2_Pipeline_loop_col_zxi2mat_fu_168_axi_data_5_out_ap_vld;
wire    grp_AXIvideo2xfMat_24_16_1080_1920_1_2_Pipeline_loop_last_hunt_fu_195_ap_start;
wire    grp_AXIvideo2xfMat_24_16_1080_1920_1_2_Pipeline_loop_last_hunt_fu_195_ap_done;
wire    grp_AXIvideo2xfMat_24_16_1080_1920_1_2_Pipeline_loop_last_hunt_fu_195_ap_idle;
wire    grp_AXIvideo2xfMat_24_16_1080_1920_1_2_Pipeline_loop_last_hunt_fu_195_ap_ready;
wire    grp_AXIvideo2xfMat_24_16_1080_1920_1_2_Pipeline_loop_last_hunt_fu_195_vstream_TREADY;
wire   [0:0] grp_AXIvideo2xfMat_24_16_1080_1920_1_2_Pipeline_loop_last_hunt_fu_195_axi_last_4_out;
wire    grp_AXIvideo2xfMat_24_16_1080_1920_1_2_Pipeline_loop_last_hunt_fu_195_axi_last_4_out_ap_vld;
wire   [23:0] grp_AXIvideo2xfMat_24_16_1080_1920_1_2_Pipeline_loop_last_hunt_fu_195_axi_data_4_out;
wire    grp_AXIvideo2xfMat_24_16_1080_1920_1_2_Pipeline_loop_last_hunt_fu_195_axi_data_4_out_ap_vld;
reg   [0:0] start_reg_124;
wire    ap_CS_fsm_state4;
wire    ap_CS_fsm_state10;
reg   [0:0] axi_last_2_reg_138;
reg    grp_AXIvideo2xfMat_24_16_1080_1920_1_2_Pipeline_loop_start_hunt_fu_148_ap_start_reg;
wire    ap_CS_fsm_state2;
wire    ap_CS_fsm_state3;
reg   [23:0] axi_data_2_fu_84;
reg    grp_AXIvideo2xfMat_24_16_1080_1920_1_2_Pipeline_loop_col_zxi2mat_fu_168_ap_start_reg;
wire    ap_CS_fsm_state5;
wire   [0:0] icmp_ln129_fu_229_p2;
wire    ap_CS_fsm_state6;
reg    grp_AXIvideo2xfMat_24_16_1080_1920_1_2_Pipeline_loop_last_hunt_fu_195_ap_start_reg;
wire    ap_CS_fsm_state8;
wire    ap_CS_fsm_state9;
reg   [0:0] axi_last_4_loc_fu_92;
reg   [10:0] i_fu_88;
wire   [10:0] i_2_fu_235_p2;
reg    ap_block_state1;
reg   [9:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
reg    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
reg    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
wire    regslice_both_vstream_V_data_V_U_apdone_blk;
wire   [23:0] vstream_TDATA_int_regslice;
wire    vstream_TVALID_int_regslice;
reg    vstream_TREADY_int_regslice;
wire    regslice_both_vstream_V_data_V_U_ack_in;
wire    regslice_both_vstream_V_keep_V_U_apdone_blk;
wire   [2:0] vstream_TKEEP_int_regslice;
wire    regslice_both_vstream_V_keep_V_U_vld_out;
wire    regslice_both_vstream_V_keep_V_U_ack_in;
wire    regslice_both_vstream_V_strb_V_U_apdone_blk;
wire   [2:0] vstream_TSTRB_int_regslice;
wire    regslice_both_vstream_V_strb_V_U_vld_out;
wire    regslice_both_vstream_V_strb_V_U_ack_in;
wire    regslice_both_vstream_V_user_V_U_apdone_blk;
wire   [0:0] vstream_TUSER_int_regslice;
wire    regslice_both_vstream_V_user_V_U_vld_out;
wire    regslice_both_vstream_V_user_V_U_ack_in;
wire    regslice_both_vstream_V_last_V_U_apdone_blk;
wire   [0:0] vstream_TLAST_int_regslice;
wire    regslice_both_vstream_V_last_V_U_vld_out;
wire    regslice_both_vstream_V_last_V_U_ack_in;
wire    regslice_both_vstream_V_id_V_U_apdone_blk;
wire   [0:0] vstream_TID_int_regslice;
wire    regslice_both_vstream_V_id_V_U_vld_out;
wire    regslice_both_vstream_V_id_V_U_ack_in;
wire    regslice_both_vstream_V_dest_V_U_apdone_blk;
wire   [0:0] vstream_TDEST_int_regslice;
wire    regslice_both_vstream_V_dest_V_U_vld_out;
wire    regslice_both_vstream_V_dest_V_U_ack_in;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 10'd1;
#0 grp_AXIvideo2xfMat_24_16_1080_1920_1_2_Pipeline_loop_start_hunt_fu_148_ap_start_reg = 1'b0;
#0 grp_AXIvideo2xfMat_24_16_1080_1920_1_2_Pipeline_loop_col_zxi2mat_fu_168_ap_start_reg = 1'b0;
#0 grp_AXIvideo2xfMat_24_16_1080_1920_1_2_Pipeline_loop_last_hunt_fu_195_ap_start_reg = 1'b0;
end

stream2mem_AXIvideo2xfMat_24_16_1080_1920_1_2_Pipeline_loop_start_hunt grp_AXIvideo2xfMat_24_16_1080_1920_1_2_Pipeline_loop_start_hunt_fu_148(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_AXIvideo2xfMat_24_16_1080_1920_1_2_Pipeline_loop_start_hunt_fu_148_ap_start),
    .ap_done(grp_AXIvideo2xfMat_24_16_1080_1920_1_2_Pipeline_loop_start_hunt_fu_148_ap_done),
    .ap_idle(grp_AXIvideo2xfMat_24_16_1080_1920_1_2_Pipeline_loop_start_hunt_fu_148_ap_idle),
    .ap_ready(grp_AXIvideo2xfMat_24_16_1080_1920_1_2_Pipeline_loop_start_hunt_fu_148_ap_ready),
    .vstream_TVALID(vstream_TVALID_int_regslice),
    .vstream_TDATA(vstream_TDATA_int_regslice),
    .vstream_TREADY(grp_AXIvideo2xfMat_24_16_1080_1920_1_2_Pipeline_loop_start_hunt_fu_148_vstream_TREADY),
    .vstream_TKEEP(vstream_TKEEP_int_regslice),
    .vstream_TSTRB(vstream_TSTRB_int_regslice),
    .vstream_TUSER(vstream_TUSER_int_regslice),
    .vstream_TLAST(vstream_TLAST_int_regslice),
    .vstream_TID(vstream_TID_int_regslice),
    .vstream_TDEST(vstream_TDEST_int_regslice),
    .axi_last_out(grp_AXIvideo2xfMat_24_16_1080_1920_1_2_Pipeline_loop_start_hunt_fu_148_axi_last_out),
    .axi_last_out_ap_vld(grp_AXIvideo2xfMat_24_16_1080_1920_1_2_Pipeline_loop_start_hunt_fu_148_axi_last_out_ap_vld),
    .axi_data_out(grp_AXIvideo2xfMat_24_16_1080_1920_1_2_Pipeline_loop_start_hunt_fu_148_axi_data_out),
    .axi_data_out_ap_vld(grp_AXIvideo2xfMat_24_16_1080_1920_1_2_Pipeline_loop_start_hunt_fu_148_axi_data_out_ap_vld)
);

stream2mem_AXIvideo2xfMat_24_16_1080_1920_1_2_Pipeline_loop_col_zxi2mat grp_AXIvideo2xfMat_24_16_1080_1920_1_2_Pipeline_loop_col_zxi2mat_fu_168(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_AXIvideo2xfMat_24_16_1080_1920_1_2_Pipeline_loop_col_zxi2mat_fu_168_ap_start),
    .ap_done(grp_AXIvideo2xfMat_24_16_1080_1920_1_2_Pipeline_loop_col_zxi2mat_fu_168_ap_done),
    .ap_idle(grp_AXIvideo2xfMat_24_16_1080_1920_1_2_Pipeline_loop_col_zxi2mat_fu_168_ap_idle),
    .ap_ready(grp_AXIvideo2xfMat_24_16_1080_1920_1_2_Pipeline_loop_col_zxi2mat_fu_168_ap_ready),
    .vstream_TVALID(vstream_TVALID_int_regslice),
    .img_data_din(grp_AXIvideo2xfMat_24_16_1080_1920_1_2_Pipeline_loop_col_zxi2mat_fu_168_img_data_din),
    .img_data_num_data_valid(2'd0),
    .img_data_fifo_cap(2'd0),
    .img_data_full_n(img_data_full_n),
    .img_data_write(grp_AXIvideo2xfMat_24_16_1080_1920_1_2_Pipeline_loop_col_zxi2mat_fu_168_img_data_write),
    .start_2(start_reg_124),
    .axi_data_2(axi_data_2_fu_84),
    .axi_last_2(axi_last_2_reg_138),
    .vstream_TDATA(vstream_TDATA_int_regslice),
    .vstream_TREADY(grp_AXIvideo2xfMat_24_16_1080_1920_1_2_Pipeline_loop_col_zxi2mat_fu_168_vstream_TREADY),
    .vstream_TKEEP(vstream_TKEEP_int_regslice),
    .vstream_TSTRB(vstream_TSTRB_int_regslice),
    .vstream_TUSER(vstream_TUSER_int_regslice),
    .vstream_TLAST(vstream_TLAST_int_regslice),
    .vstream_TID(vstream_TID_int_regslice),
    .vstream_TDEST(vstream_TDEST_int_regslice),
    .last_out(grp_AXIvideo2xfMat_24_16_1080_1920_1_2_Pipeline_loop_col_zxi2mat_fu_168_last_out),
    .last_out_ap_vld(grp_AXIvideo2xfMat_24_16_1080_1920_1_2_Pipeline_loop_col_zxi2mat_fu_168_last_out_ap_vld),
    .axi_data_5_out(grp_AXIvideo2xfMat_24_16_1080_1920_1_2_Pipeline_loop_col_zxi2mat_fu_168_axi_data_5_out),
    .axi_data_5_out_ap_vld(grp_AXIvideo2xfMat_24_16_1080_1920_1_2_Pipeline_loop_col_zxi2mat_fu_168_axi_data_5_out_ap_vld)
);

stream2mem_AXIvideo2xfMat_24_16_1080_1920_1_2_Pipeline_loop_last_hunt grp_AXIvideo2xfMat_24_16_1080_1920_1_2_Pipeline_loop_last_hunt_fu_195(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_AXIvideo2xfMat_24_16_1080_1920_1_2_Pipeline_loop_last_hunt_fu_195_ap_start),
    .ap_done(grp_AXIvideo2xfMat_24_16_1080_1920_1_2_Pipeline_loop_last_hunt_fu_195_ap_done),
    .ap_idle(grp_AXIvideo2xfMat_24_16_1080_1920_1_2_Pipeline_loop_last_hunt_fu_195_ap_idle),
    .ap_ready(grp_AXIvideo2xfMat_24_16_1080_1920_1_2_Pipeline_loop_last_hunt_fu_195_ap_ready),
    .vstream_TVALID(vstream_TVALID_int_regslice),
    .axi_last_2_lcssa(grp_AXIvideo2xfMat_24_16_1080_1920_1_2_Pipeline_loop_col_zxi2mat_fu_168_last_out),
    .axi_data_2_lcssa(grp_AXIvideo2xfMat_24_16_1080_1920_1_2_Pipeline_loop_col_zxi2mat_fu_168_axi_data_5_out),
    .last_0_lcssa(grp_AXIvideo2xfMat_24_16_1080_1920_1_2_Pipeline_loop_col_zxi2mat_fu_168_last_out),
    .vstream_TDATA(vstream_TDATA_int_regslice),
    .vstream_TREADY(grp_AXIvideo2xfMat_24_16_1080_1920_1_2_Pipeline_loop_last_hunt_fu_195_vstream_TREADY),
    .vstream_TKEEP(vstream_TKEEP_int_regslice),
    .vstream_TSTRB(vstream_TSTRB_int_regslice),
    .vstream_TUSER(vstream_TUSER_int_regslice),
    .vstream_TLAST(vstream_TLAST_int_regslice),
    .vstream_TID(vstream_TID_int_regslice),
    .vstream_TDEST(vstream_TDEST_int_regslice),
    .axi_last_4_out(grp_AXIvideo2xfMat_24_16_1080_1920_1_2_Pipeline_loop_last_hunt_fu_195_axi_last_4_out),
    .axi_last_4_out_ap_vld(grp_AXIvideo2xfMat_24_16_1080_1920_1_2_Pipeline_loop_last_hunt_fu_195_axi_last_4_out_ap_vld),
    .axi_data_4_out(grp_AXIvideo2xfMat_24_16_1080_1920_1_2_Pipeline_loop_last_hunt_fu_195_axi_data_4_out),
    .axi_data_4_out_ap_vld(grp_AXIvideo2xfMat_24_16_1080_1920_1_2_Pipeline_loop_last_hunt_fu_195_axi_data_4_out_ap_vld)
);

stream2mem_regslice_both #(
    .DataWidth( 24 ))
regslice_both_vstream_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(vstream_TDATA),
    .vld_in(vstream_TVALID),
    .ack_in(regslice_both_vstream_V_data_V_U_ack_in),
    .data_out(vstream_TDATA_int_regslice),
    .vld_out(vstream_TVALID_int_regslice),
    .ack_out(vstream_TREADY_int_regslice),
    .apdone_blk(regslice_both_vstream_V_data_V_U_apdone_blk)
);

stream2mem_regslice_both #(
    .DataWidth( 3 ))
regslice_both_vstream_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(vstream_TKEEP),
    .vld_in(vstream_TVALID),
    .ack_in(regslice_both_vstream_V_keep_V_U_ack_in),
    .data_out(vstream_TKEEP_int_regslice),
    .vld_out(regslice_both_vstream_V_keep_V_U_vld_out),
    .ack_out(vstream_TREADY_int_regslice),
    .apdone_blk(regslice_both_vstream_V_keep_V_U_apdone_blk)
);

stream2mem_regslice_both #(
    .DataWidth( 3 ))
regslice_both_vstream_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(vstream_TSTRB),
    .vld_in(vstream_TVALID),
    .ack_in(regslice_both_vstream_V_strb_V_U_ack_in),
    .data_out(vstream_TSTRB_int_regslice),
    .vld_out(regslice_both_vstream_V_strb_V_U_vld_out),
    .ack_out(vstream_TREADY_int_regslice),
    .apdone_blk(regslice_both_vstream_V_strb_V_U_apdone_blk)
);

stream2mem_regslice_both #(
    .DataWidth( 1 ))
regslice_both_vstream_V_user_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(vstream_TUSER),
    .vld_in(vstream_TVALID),
    .ack_in(regslice_both_vstream_V_user_V_U_ack_in),
    .data_out(vstream_TUSER_int_regslice),
    .vld_out(regslice_both_vstream_V_user_V_U_vld_out),
    .ack_out(vstream_TREADY_int_regslice),
    .apdone_blk(regslice_both_vstream_V_user_V_U_apdone_blk)
);

stream2mem_regslice_both #(
    .DataWidth( 1 ))
regslice_both_vstream_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(vstream_TLAST),
    .vld_in(vstream_TVALID),
    .ack_in(regslice_both_vstream_V_last_V_U_ack_in),
    .data_out(vstream_TLAST_int_regslice),
    .vld_out(regslice_both_vstream_V_last_V_U_vld_out),
    .ack_out(vstream_TREADY_int_regslice),
    .apdone_blk(regslice_both_vstream_V_last_V_U_apdone_blk)
);

stream2mem_regslice_both #(
    .DataWidth( 1 ))
regslice_both_vstream_V_id_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(vstream_TID),
    .vld_in(vstream_TVALID),
    .ack_in(regslice_both_vstream_V_id_V_U_ack_in),
    .data_out(vstream_TID_int_regslice),
    .vld_out(regslice_both_vstream_V_id_V_U_vld_out),
    .ack_out(vstream_TREADY_int_regslice),
    .apdone_blk(regslice_both_vstream_V_id_V_U_apdone_blk)
);

stream2mem_regslice_both #(
    .DataWidth( 1 ))
regslice_both_vstream_V_dest_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(vstream_TDEST),
    .vld_in(vstream_TVALID),
    .ack_in(regslice_both_vstream_V_dest_V_U_ack_in),
    .data_out(vstream_TDEST_int_regslice),
    .vld_out(regslice_both_vstream_V_dest_V_U_vld_out),
    .ack_out(vstream_TREADY_int_regslice),
    .apdone_blk(regslice_both_vstream_V_dest_V_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_state5) & (icmp_ln129_fu_229_p2 == 1'd1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_AXIvideo2xfMat_24_16_1080_1920_1_2_Pipeline_loop_col_zxi2mat_fu_168_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state5) & (icmp_ln129_fu_229_p2 == 1'd0))) begin
            grp_AXIvideo2xfMat_24_16_1080_1920_1_2_Pipeline_loop_col_zxi2mat_fu_168_ap_start_reg <= 1'b1;
        end else if ((grp_AXIvideo2xfMat_24_16_1080_1920_1_2_Pipeline_loop_col_zxi2mat_fu_168_ap_ready == 1'b1)) begin
            grp_AXIvideo2xfMat_24_16_1080_1920_1_2_Pipeline_loop_col_zxi2mat_fu_168_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_AXIvideo2xfMat_24_16_1080_1920_1_2_Pipeline_loop_last_hunt_fu_195_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state8)) begin
            grp_AXIvideo2xfMat_24_16_1080_1920_1_2_Pipeline_loop_last_hunt_fu_195_ap_start_reg <= 1'b1;
        end else if ((grp_AXIvideo2xfMat_24_16_1080_1920_1_2_Pipeline_loop_last_hunt_fu_195_ap_ready == 1'b1)) begin
            grp_AXIvideo2xfMat_24_16_1080_1920_1_2_Pipeline_loop_last_hunt_fu_195_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_AXIvideo2xfMat_24_16_1080_1920_1_2_Pipeline_loop_start_hunt_fu_148_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state2)) begin
            grp_AXIvideo2xfMat_24_16_1080_1920_1_2_Pipeline_loop_start_hunt_fu_148_ap_start_reg <= 1'b1;
        end else if ((grp_AXIvideo2xfMat_24_16_1080_1920_1_2_Pipeline_loop_start_hunt_fu_148_ap_ready == 1'b1)) begin
            grp_AXIvideo2xfMat_24_16_1080_1920_1_2_Pipeline_loop_start_hunt_fu_148_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state9) & (grp_AXIvideo2xfMat_24_16_1080_1920_1_2_Pipeline_loop_last_hunt_fu_195_axi_data_4_out_ap_vld == 1'b1))) begin
        axi_data_2_fu_84 <= grp_AXIvideo2xfMat_24_16_1080_1920_1_2_Pipeline_loop_last_hunt_fu_195_axi_data_4_out;
    end else if (((grp_AXIvideo2xfMat_24_16_1080_1920_1_2_Pipeline_loop_start_hunt_fu_148_axi_data_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        axi_data_2_fu_84 <= grp_AXIvideo2xfMat_24_16_1080_1920_1_2_Pipeline_loop_start_hunt_fu_148_axi_data_out;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        axi_last_2_reg_138 <= axi_last_4_loc_fu_92;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        axi_last_2_reg_138 <= grp_AXIvideo2xfMat_24_16_1080_1920_1_2_Pipeline_loop_start_hunt_fu_148_axi_last_out;
    end
end

always @ (posedge ap_clk) begin
    if ((~((img_cols_c_full_n == 1'b0) | (img_rows_c_full_n == 1'b0) | (ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        i_fu_88 <= 11'd0;
    end else if (((1'b1 == ap_CS_fsm_state5) & (icmp_ln129_fu_229_p2 == 1'd0))) begin
        i_fu_88 <= i_2_fu_235_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        start_reg_124 <= 1'd0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        start_reg_124 <= 1'd1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state9) & (grp_AXIvideo2xfMat_24_16_1080_1920_1_2_Pipeline_loop_last_hunt_fu_195_axi_last_4_out_ap_vld == 1'b1))) begin
        axi_last_4_loc_fu_92 <= grp_AXIvideo2xfMat_24_16_1080_1920_1_2_Pipeline_loop_last_hunt_fu_195_axi_last_4_out;
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

always @ (*) begin
    if (((img_cols_c_full_n == 1'b0) | (img_rows_c_full_n == 1'b0) | (ap_done_reg == 1'b1) | (ap_start == 1'b0))) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((grp_AXIvideo2xfMat_24_16_1080_1920_1_2_Pipeline_loop_start_hunt_fu_148_ap_done == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

always @ (*) begin
    if ((grp_AXIvideo2xfMat_24_16_1080_1920_1_2_Pipeline_loop_col_zxi2mat_fu_168_ap_done == 1'b0)) begin
        ap_ST_fsm_state6_blk = 1'b1;
    end else begin
        ap_ST_fsm_state6_blk = 1'b0;
    end
end

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

always @ (*) begin
    if ((grp_AXIvideo2xfMat_24_16_1080_1920_1_2_Pipeline_loop_last_hunt_fu_195_ap_done == 1'b0)) begin
        ap_ST_fsm_state9_blk = 1'b1;
    end else begin
        ap_ST_fsm_state9_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) & (icmp_ln129_fu_229_p2 == 1'd1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) & (icmp_ln129_fu_229_p2 == 1'd1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        img_cols_c_blk_n = img_cols_c_full_n;
    end else begin
        img_cols_c_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((img_cols_c_full_n == 1'b0) | (img_rows_c_full_n == 1'b0) | (ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        img_cols_c_write = 1'b1;
    end else begin
        img_cols_c_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        img_data_write = grp_AXIvideo2xfMat_24_16_1080_1920_1_2_Pipeline_loop_col_zxi2mat_fu_168_img_data_write;
    end else begin
        img_data_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        img_rows_c_blk_n = img_rows_c_full_n;
    end else begin
        img_rows_c_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((img_cols_c_full_n == 1'b0) | (img_rows_c_full_n == 1'b0) | (ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        img_rows_c_write = 1'b1;
    end else begin
        img_rows_c_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        vstream_TREADY_int_regslice = grp_AXIvideo2xfMat_24_16_1080_1920_1_2_Pipeline_loop_last_hunt_fu_195_vstream_TREADY;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        vstream_TREADY_int_regslice = grp_AXIvideo2xfMat_24_16_1080_1920_1_2_Pipeline_loop_col_zxi2mat_fu_168_vstream_TREADY;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        vstream_TREADY_int_regslice = grp_AXIvideo2xfMat_24_16_1080_1920_1_2_Pipeline_loop_start_hunt_fu_148_vstream_TREADY;
    end else begin
        vstream_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((img_cols_c_full_n == 1'b0) | (img_rows_c_full_n == 1'b0) | (ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if (((grp_AXIvideo2xfMat_24_16_1080_1920_1_2_Pipeline_loop_start_hunt_fu_148_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            if (((1'b1 == ap_CS_fsm_state5) & (icmp_ln129_fu_229_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state6 : begin
            if (((grp_AXIvideo2xfMat_24_16_1080_1920_1_2_Pipeline_loop_col_zxi2mat_fu_168_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            if (((1'b1 == ap_CS_fsm_state9) & (grp_AXIvideo2xfMat_24_16_1080_1920_1_2_Pipeline_loop_last_hunt_fu_195_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_block_state1 = ((img_cols_c_full_n == 1'b0) | (img_rows_c_full_n == 1'b0) | (ap_done_reg == 1'b1) | (ap_start == 1'b0));
end

assign grp_AXIvideo2xfMat_24_16_1080_1920_1_2_Pipeline_loop_col_zxi2mat_fu_168_ap_start = grp_AXIvideo2xfMat_24_16_1080_1920_1_2_Pipeline_loop_col_zxi2mat_fu_168_ap_start_reg;

assign grp_AXIvideo2xfMat_24_16_1080_1920_1_2_Pipeline_loop_last_hunt_fu_195_ap_start = grp_AXIvideo2xfMat_24_16_1080_1920_1_2_Pipeline_loop_last_hunt_fu_195_ap_start_reg;

assign grp_AXIvideo2xfMat_24_16_1080_1920_1_2_Pipeline_loop_start_hunt_fu_148_ap_start = grp_AXIvideo2xfMat_24_16_1080_1920_1_2_Pipeline_loop_start_hunt_fu_148_ap_start_reg;

assign i_2_fu_235_p2 = (i_fu_88 + 11'd1);

assign icmp_ln129_fu_229_p2 = ((i_fu_88 == 11'd1080) ? 1'b1 : 1'b0);

assign img_cols_c_din = 8'd128;

assign img_data_din = grp_AXIvideo2xfMat_24_16_1080_1920_1_2_Pipeline_loop_col_zxi2mat_fu_168_img_data_din;

assign img_rows_c_din = 11'd1080;

assign vstream_TREADY = regslice_both_vstream_V_data_V_U_ack_in;

endmodule //stream2mem_AXIvideo2xfMat_24_16_1080_1920_1_2_s
