// ==============================================================
// Generated by Vitis HLS v2023.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module mem2stream_dataflow_in_loop_VITIS_LOOP_38_1_1 (
        baseAddr_address0,
        baseAddr_ce0,
        baseAddr_d0,
        baseAddr_q0,
        baseAddr_we0,
        m_axi_gmem_AWVALID,
        m_axi_gmem_AWREADY,
        m_axi_gmem_AWADDR,
        m_axi_gmem_AWID,
        m_axi_gmem_AWLEN,
        m_axi_gmem_AWSIZE,
        m_axi_gmem_AWBURST,
        m_axi_gmem_AWLOCK,
        m_axi_gmem_AWCACHE,
        m_axi_gmem_AWPROT,
        m_axi_gmem_AWQOS,
        m_axi_gmem_AWREGION,
        m_axi_gmem_AWUSER,
        m_axi_gmem_WVALID,
        m_axi_gmem_WREADY,
        m_axi_gmem_WDATA,
        m_axi_gmem_WSTRB,
        m_axi_gmem_WLAST,
        m_axi_gmem_WID,
        m_axi_gmem_WUSER,
        m_axi_gmem_ARVALID,
        m_axi_gmem_ARREADY,
        m_axi_gmem_ARADDR,
        m_axi_gmem_ARID,
        m_axi_gmem_ARLEN,
        m_axi_gmem_ARSIZE,
        m_axi_gmem_ARBURST,
        m_axi_gmem_ARLOCK,
        m_axi_gmem_ARCACHE,
        m_axi_gmem_ARPROT,
        m_axi_gmem_ARQOS,
        m_axi_gmem_ARREGION,
        m_axi_gmem_ARUSER,
        m_axi_gmem_RVALID,
        m_axi_gmem_RREADY,
        m_axi_gmem_RDATA,
        m_axi_gmem_RLAST,
        m_axi_gmem_RID,
        m_axi_gmem_RFIFONUM,
        m_axi_gmem_RUSER,
        m_axi_gmem_RRESP,
        m_axi_gmem_BVALID,
        m_axi_gmem_BREADY,
        m_axi_gmem_BRESP,
        m_axi_gmem_BID,
        m_axi_gmem_BUSER,
        pMemPort,
        row,
        p_read,
        p_read1,
        img_data_din,
        img_data_full_n,
        img_data_write,
        index,
        ap_clk,
        ap_rst,
        p_read1_ap_vld,
        index_ap_vld,
        ap_start,
        pMemPort_ap_vld,
        row_ap_vld,
        p_read_ap_vld,
        ap_done,
        ap_ready,
        ap_idle,
        ap_continue
);


output  [1:0] baseAddr_address0;
output   baseAddr_ce0;
output  [31:0] baseAddr_d0;
input  [31:0] baseAddr_q0;
output   baseAddr_we0;
output   m_axi_gmem_AWVALID;
input   m_axi_gmem_AWREADY;
output  [63:0] m_axi_gmem_AWADDR;
output  [0:0] m_axi_gmem_AWID;
output  [31:0] m_axi_gmem_AWLEN;
output  [2:0] m_axi_gmem_AWSIZE;
output  [1:0] m_axi_gmem_AWBURST;
output  [1:0] m_axi_gmem_AWLOCK;
output  [3:0] m_axi_gmem_AWCACHE;
output  [2:0] m_axi_gmem_AWPROT;
output  [3:0] m_axi_gmem_AWQOS;
output  [3:0] m_axi_gmem_AWREGION;
output  [0:0] m_axi_gmem_AWUSER;
output   m_axi_gmem_WVALID;
input   m_axi_gmem_WREADY;
output  [31:0] m_axi_gmem_WDATA;
output  [3:0] m_axi_gmem_WSTRB;
output   m_axi_gmem_WLAST;
output  [0:0] m_axi_gmem_WID;
output  [0:0] m_axi_gmem_WUSER;
output   m_axi_gmem_ARVALID;
input   m_axi_gmem_ARREADY;
output  [63:0] m_axi_gmem_ARADDR;
output  [0:0] m_axi_gmem_ARID;
output  [31:0] m_axi_gmem_ARLEN;
output  [2:0] m_axi_gmem_ARSIZE;
output  [1:0] m_axi_gmem_ARBURST;
output  [1:0] m_axi_gmem_ARLOCK;
output  [3:0] m_axi_gmem_ARCACHE;
output  [2:0] m_axi_gmem_ARPROT;
output  [3:0] m_axi_gmem_ARQOS;
output  [3:0] m_axi_gmem_ARREGION;
output  [0:0] m_axi_gmem_ARUSER;
input   m_axi_gmem_RVALID;
output   m_axi_gmem_RREADY;
input  [31:0] m_axi_gmem_RDATA;
input   m_axi_gmem_RLAST;
input  [0:0] m_axi_gmem_RID;
input  [8:0] m_axi_gmem_RFIFONUM;
input  [0:0] m_axi_gmem_RUSER;
input  [1:0] m_axi_gmem_RRESP;
input   m_axi_gmem_BVALID;
output   m_axi_gmem_BREADY;
input  [1:0] m_axi_gmem_BRESP;
input  [0:0] m_axi_gmem_BID;
input  [0:0] m_axi_gmem_BUSER;
input  [63:0] pMemPort;
input  [10:0] row;
input  [10:0] p_read;
input  [7:0] p_read1;
output  [23:0] img_data_din;
input   img_data_full_n;
output   img_data_write;
input  [31:0] index;
input   ap_clk;
input   ap_rst;
input   p_read1_ap_vld;
input   index_ap_vld;
input   ap_start;
input   pMemPort_ap_vld;
input   row_ap_vld;
input   p_read_ap_vld;
output   ap_done;
output   ap_ready;
output   ap_idle;
input   ap_continue;

wire    dataflow_in_loop_VITIS_LOOP_38_1_1_Block_newFuncRoot17_proc3_U0_ap_start;
wire    dataflow_in_loop_VITIS_LOOP_38_1_1_Block_newFuncRoot17_proc3_U0_ap_done;
wire    dataflow_in_loop_VITIS_LOOP_38_1_1_Block_newFuncRoot17_proc3_U0_ap_continue;
wire    dataflow_in_loop_VITIS_LOOP_38_1_1_Block_newFuncRoot17_proc3_U0_ap_idle;
wire    dataflow_in_loop_VITIS_LOOP_38_1_1_Block_newFuncRoot17_proc3_U0_ap_ready;
wire   [1:0] dataflow_in_loop_VITIS_LOOP_38_1_1_Block_newFuncRoot17_proc3_U0_baseAddr_address0;
wire    dataflow_in_loop_VITIS_LOOP_38_1_1_Block_newFuncRoot17_proc3_U0_baseAddr_ce0;
wire   [31:0] dataflow_in_loop_VITIS_LOOP_38_1_1_Block_newFuncRoot17_proc3_U0_ap_return_0;
wire   [29:0] dataflow_in_loop_VITIS_LOOP_38_1_1_Block_newFuncRoot17_proc3_U0_ap_return_1;
wire    ap_channel_done_trunc_ln42_loc_i_i_channel;
wire    trunc_ln42_loc_i_i_channel_full_n;
reg    ap_sync_reg_channel_write_trunc_ln42_loc_i_i_channel;
wire    ap_sync_channel_write_trunc_ln42_loc_i_i_channel;
wire    ap_channel_done_p_cast16_loc_i_i_channel;
wire    p_cast16_loc_i_i_channel_full_n;
reg    ap_sync_reg_channel_write_p_cast16_loc_i_i_channel;
wire    ap_sync_channel_write_p_cast16_loc_i_i_channel;
wire    readmem4_U0_ap_start;
wire    readmem4_U0_ap_done;
wire    readmem4_U0_ap_continue;
wire    readmem4_U0_ap_idle;
wire    readmem4_U0_ap_ready;
wire    readmem4_U0_m_axi_gmem_AWVALID;
wire   [63:0] readmem4_U0_m_axi_gmem_AWADDR;
wire   [0:0] readmem4_U0_m_axi_gmem_AWID;
wire   [31:0] readmem4_U0_m_axi_gmem_AWLEN;
wire   [2:0] readmem4_U0_m_axi_gmem_AWSIZE;
wire   [1:0] readmem4_U0_m_axi_gmem_AWBURST;
wire   [1:0] readmem4_U0_m_axi_gmem_AWLOCK;
wire   [3:0] readmem4_U0_m_axi_gmem_AWCACHE;
wire   [2:0] readmem4_U0_m_axi_gmem_AWPROT;
wire   [3:0] readmem4_U0_m_axi_gmem_AWQOS;
wire   [3:0] readmem4_U0_m_axi_gmem_AWREGION;
wire   [0:0] readmem4_U0_m_axi_gmem_AWUSER;
wire    readmem4_U0_m_axi_gmem_WVALID;
wire   [31:0] readmem4_U0_m_axi_gmem_WDATA;
wire   [3:0] readmem4_U0_m_axi_gmem_WSTRB;
wire    readmem4_U0_m_axi_gmem_WLAST;
wire   [0:0] readmem4_U0_m_axi_gmem_WID;
wire   [0:0] readmem4_U0_m_axi_gmem_WUSER;
wire    readmem4_U0_m_axi_gmem_ARVALID;
wire   [63:0] readmem4_U0_m_axi_gmem_ARADDR;
wire   [0:0] readmem4_U0_m_axi_gmem_ARID;
wire   [31:0] readmem4_U0_m_axi_gmem_ARLEN;
wire   [2:0] readmem4_U0_m_axi_gmem_ARSIZE;
wire   [1:0] readmem4_U0_m_axi_gmem_ARBURST;
wire   [1:0] readmem4_U0_m_axi_gmem_ARLOCK;
wire   [3:0] readmem4_U0_m_axi_gmem_ARCACHE;
wire   [2:0] readmem4_U0_m_axi_gmem_ARPROT;
wire   [3:0] readmem4_U0_m_axi_gmem_ARQOS;
wire   [3:0] readmem4_U0_m_axi_gmem_ARREGION;
wire   [0:0] readmem4_U0_m_axi_gmem_ARUSER;
wire    readmem4_U0_m_axi_gmem_RREADY;
wire    readmem4_U0_m_axi_gmem_BREADY;
wire   [31:0] readmem4_U0_cacheBuff_i_i_din;
wire    readmem4_U0_cacheBuff_i_i_write;
wire    dataflow_in_loop_VITIS_LOOP_38_1_1_Loop_VITIS_LOOP_43_2_proc5_U0_ap_start;
wire    dataflow_in_loop_VITIS_LOOP_38_1_1_Loop_VITIS_LOOP_43_2_proc5_U0_ap_done;
wire    dataflow_in_loop_VITIS_LOOP_38_1_1_Loop_VITIS_LOOP_43_2_proc5_U0_ap_continue;
wire    dataflow_in_loop_VITIS_LOOP_38_1_1_Loop_VITIS_LOOP_43_2_proc5_U0_ap_idle;
wire    dataflow_in_loop_VITIS_LOOP_38_1_1_Loop_VITIS_LOOP_43_2_proc5_U0_ap_ready;
wire    dataflow_in_loop_VITIS_LOOP_38_1_1_Loop_VITIS_LOOP_43_2_proc5_U0_cacheBuff_read;
wire   [23:0] dataflow_in_loop_VITIS_LOOP_38_1_1_Loop_VITIS_LOOP_43_2_proc5_U0_img_data_din;
wire    dataflow_in_loop_VITIS_LOOP_38_1_1_Loop_VITIS_LOOP_43_2_proc5_U0_img_data_write;
wire   [31:0] p_cast16_loc_i_i_channel_dout;
wire   [2:0] p_cast16_loc_i_i_channel_num_data_valid;
wire   [2:0] p_cast16_loc_i_i_channel_fifo_cap;
wire    p_cast16_loc_i_i_channel_empty_n;
wire   [29:0] trunc_ln42_loc_i_i_channel_dout;
wire   [1:0] trunc_ln42_loc_i_i_channel_num_data_valid;
wire   [1:0] trunc_ln42_loc_i_i_channel_fifo_cap;
wire    trunc_ln42_loc_i_i_channel_empty_n;
wire    cacheBuff_full_n;
wire   [31:0] cacheBuff_dout;
wire   [12:0] cacheBuff_num_data_valid;
wire   [12:0] cacheBuff_fifo_cap;
wire    cacheBuff_empty_n;
wire    ap_sync_ready;
reg    ap_sync_reg_dataflow_in_loop_VITIS_LOOP_38_1_1_Block_newFuncRoot17_proc3_U0_ap_ready;
wire    ap_sync_dataflow_in_loop_VITIS_LOOP_38_1_1_Block_newFuncRoot17_proc3_U0_ap_ready;
reg    ap_sync_reg_readmem4_U0_ap_ready;
wire    ap_sync_readmem4_U0_ap_ready;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_sync_reg_channel_write_trunc_ln42_loc_i_i_channel = 1'b0;
#0 ap_sync_reg_channel_write_p_cast16_loc_i_i_channel = 1'b0;
#0 ap_sync_reg_dataflow_in_loop_VITIS_LOOP_38_1_1_Block_newFuncRoot17_proc3_U0_ap_ready = 1'b0;
#0 ap_sync_reg_readmem4_U0_ap_ready = 1'b0;
end

mem2stream_dataflow_in_loop_VITIS_LOOP_38_1_1_Block_newFuncRoot17_proc3 dataflow_in_loop_VITIS_LOOP_38_1_1_Block_newFuncRoot17_proc3_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(dataflow_in_loop_VITIS_LOOP_38_1_1_Block_newFuncRoot17_proc3_U0_ap_start),
    .ap_done(dataflow_in_loop_VITIS_LOOP_38_1_1_Block_newFuncRoot17_proc3_U0_ap_done),
    .ap_continue(dataflow_in_loop_VITIS_LOOP_38_1_1_Block_newFuncRoot17_proc3_U0_ap_continue),
    .ap_idle(dataflow_in_loop_VITIS_LOOP_38_1_1_Block_newFuncRoot17_proc3_U0_ap_idle),
    .ap_ready(dataflow_in_loop_VITIS_LOOP_38_1_1_Block_newFuncRoot17_proc3_U0_ap_ready),
    .p_read(p_read1),
    .baseAddr_address0(dataflow_in_loop_VITIS_LOOP_38_1_1_Block_newFuncRoot17_proc3_U0_baseAddr_address0),
    .baseAddr_ce0(dataflow_in_loop_VITIS_LOOP_38_1_1_Block_newFuncRoot17_proc3_U0_baseAddr_ce0),
    .baseAddr_q0(baseAddr_q0),
    .index(index),
    .ap_return_0(dataflow_in_loop_VITIS_LOOP_38_1_1_Block_newFuncRoot17_proc3_U0_ap_return_0),
    .ap_return_1(dataflow_in_loop_VITIS_LOOP_38_1_1_Block_newFuncRoot17_proc3_U0_ap_return_1)
);

mem2stream_readmem4 readmem4_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(readmem4_U0_ap_start),
    .ap_done(readmem4_U0_ap_done),
    .ap_continue(readmem4_U0_ap_continue),
    .ap_idle(readmem4_U0_ap_idle),
    .ap_ready(readmem4_U0_ap_ready),
    .m_axi_gmem_AWVALID(readmem4_U0_m_axi_gmem_AWVALID),
    .m_axi_gmem_AWREADY(1'b0),
    .m_axi_gmem_AWADDR(readmem4_U0_m_axi_gmem_AWADDR),
    .m_axi_gmem_AWID(readmem4_U0_m_axi_gmem_AWID),
    .m_axi_gmem_AWLEN(readmem4_U0_m_axi_gmem_AWLEN),
    .m_axi_gmem_AWSIZE(readmem4_U0_m_axi_gmem_AWSIZE),
    .m_axi_gmem_AWBURST(readmem4_U0_m_axi_gmem_AWBURST),
    .m_axi_gmem_AWLOCK(readmem4_U0_m_axi_gmem_AWLOCK),
    .m_axi_gmem_AWCACHE(readmem4_U0_m_axi_gmem_AWCACHE),
    .m_axi_gmem_AWPROT(readmem4_U0_m_axi_gmem_AWPROT),
    .m_axi_gmem_AWQOS(readmem4_U0_m_axi_gmem_AWQOS),
    .m_axi_gmem_AWREGION(readmem4_U0_m_axi_gmem_AWREGION),
    .m_axi_gmem_AWUSER(readmem4_U0_m_axi_gmem_AWUSER),
    .m_axi_gmem_WVALID(readmem4_U0_m_axi_gmem_WVALID),
    .m_axi_gmem_WREADY(1'b0),
    .m_axi_gmem_WDATA(readmem4_U0_m_axi_gmem_WDATA),
    .m_axi_gmem_WSTRB(readmem4_U0_m_axi_gmem_WSTRB),
    .m_axi_gmem_WLAST(readmem4_U0_m_axi_gmem_WLAST),
    .m_axi_gmem_WID(readmem4_U0_m_axi_gmem_WID),
    .m_axi_gmem_WUSER(readmem4_U0_m_axi_gmem_WUSER),
    .m_axi_gmem_ARVALID(readmem4_U0_m_axi_gmem_ARVALID),
    .m_axi_gmem_ARREADY(m_axi_gmem_ARREADY),
    .m_axi_gmem_ARADDR(readmem4_U0_m_axi_gmem_ARADDR),
    .m_axi_gmem_ARID(readmem4_U0_m_axi_gmem_ARID),
    .m_axi_gmem_ARLEN(readmem4_U0_m_axi_gmem_ARLEN),
    .m_axi_gmem_ARSIZE(readmem4_U0_m_axi_gmem_ARSIZE),
    .m_axi_gmem_ARBURST(readmem4_U0_m_axi_gmem_ARBURST),
    .m_axi_gmem_ARLOCK(readmem4_U0_m_axi_gmem_ARLOCK),
    .m_axi_gmem_ARCACHE(readmem4_U0_m_axi_gmem_ARCACHE),
    .m_axi_gmem_ARPROT(readmem4_U0_m_axi_gmem_ARPROT),
    .m_axi_gmem_ARQOS(readmem4_U0_m_axi_gmem_ARQOS),
    .m_axi_gmem_ARREGION(readmem4_U0_m_axi_gmem_ARREGION),
    .m_axi_gmem_ARUSER(readmem4_U0_m_axi_gmem_ARUSER),
    .m_axi_gmem_RVALID(m_axi_gmem_RVALID),
    .m_axi_gmem_RREADY(readmem4_U0_m_axi_gmem_RREADY),
    .m_axi_gmem_RDATA(m_axi_gmem_RDATA),
    .m_axi_gmem_RLAST(m_axi_gmem_RLAST),
    .m_axi_gmem_RID(m_axi_gmem_RID),
    .m_axi_gmem_RFIFONUM(m_axi_gmem_RFIFONUM),
    .m_axi_gmem_RUSER(m_axi_gmem_RUSER),
    .m_axi_gmem_RRESP(m_axi_gmem_RRESP),
    .m_axi_gmem_BVALID(1'b0),
    .m_axi_gmem_BREADY(readmem4_U0_m_axi_gmem_BREADY),
    .m_axi_gmem_BRESP(2'd0),
    .m_axi_gmem_BID(1'd0),
    .m_axi_gmem_BUSER(1'd0),
    .pMemPort(pMemPort),
    .p_read(trunc_ln42_loc_i_i_channel_dout),
    .row(row),
    .p_read1(p_read),
    .cacheBuff_i_i_din(readmem4_U0_cacheBuff_i_i_din),
    .cacheBuff_i_i_num_data_valid(cacheBuff_num_data_valid),
    .cacheBuff_i_i_fifo_cap(cacheBuff_fifo_cap),
    .cacheBuff_i_i_full_n(cacheBuff_full_n),
    .cacheBuff_i_i_write(readmem4_U0_cacheBuff_i_i_write),
    .p_read2(p_read1)
);

mem2stream_dataflow_in_loop_VITIS_LOOP_38_1_1_Loop_VITIS_LOOP_43_2_proc5 dataflow_in_loop_VITIS_LOOP_38_1_1_Loop_VITIS_LOOP_43_2_proc5_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(dataflow_in_loop_VITIS_LOOP_38_1_1_Loop_VITIS_LOOP_43_2_proc5_U0_ap_start),
    .ap_done(dataflow_in_loop_VITIS_LOOP_38_1_1_Loop_VITIS_LOOP_43_2_proc5_U0_ap_done),
    .ap_continue(dataflow_in_loop_VITIS_LOOP_38_1_1_Loop_VITIS_LOOP_43_2_proc5_U0_ap_continue),
    .ap_idle(dataflow_in_loop_VITIS_LOOP_38_1_1_Loop_VITIS_LOOP_43_2_proc5_U0_ap_idle),
    .ap_ready(dataflow_in_loop_VITIS_LOOP_38_1_1_Loop_VITIS_LOOP_43_2_proc5_U0_ap_ready),
    .p_read(p_cast16_loc_i_i_channel_dout),
    .cacheBuff_dout(cacheBuff_dout),
    .cacheBuff_num_data_valid(cacheBuff_num_data_valid),
    .cacheBuff_fifo_cap(cacheBuff_fifo_cap),
    .cacheBuff_empty_n(cacheBuff_empty_n),
    .cacheBuff_read(dataflow_in_loop_VITIS_LOOP_38_1_1_Loop_VITIS_LOOP_43_2_proc5_U0_cacheBuff_read),
    .img_data_din(dataflow_in_loop_VITIS_LOOP_38_1_1_Loop_VITIS_LOOP_43_2_proc5_U0_img_data_din),
    .img_data_num_data_valid(2'd0),
    .img_data_fifo_cap(2'd0),
    .img_data_full_n(img_data_full_n),
    .img_data_write(dataflow_in_loop_VITIS_LOOP_38_1_1_Loop_VITIS_LOOP_43_2_proc5_U0_img_data_write)
);

mem2stream_fifo_w32_d3_S p_cast16_loc_i_i_channel_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(dataflow_in_loop_VITIS_LOOP_38_1_1_Block_newFuncRoot17_proc3_U0_ap_return_0),
    .if_full_n(p_cast16_loc_i_i_channel_full_n),
    .if_write(ap_channel_done_p_cast16_loc_i_i_channel),
    .if_dout(p_cast16_loc_i_i_channel_dout),
    .if_num_data_valid(p_cast16_loc_i_i_channel_num_data_valid),
    .if_fifo_cap(p_cast16_loc_i_i_channel_fifo_cap),
    .if_empty_n(p_cast16_loc_i_i_channel_empty_n),
    .if_read(dataflow_in_loop_VITIS_LOOP_38_1_1_Loop_VITIS_LOOP_43_2_proc5_U0_ap_ready)
);

mem2stream_fifo_w30_d2_S trunc_ln42_loc_i_i_channel_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(dataflow_in_loop_VITIS_LOOP_38_1_1_Block_newFuncRoot17_proc3_U0_ap_return_1),
    .if_full_n(trunc_ln42_loc_i_i_channel_full_n),
    .if_write(ap_channel_done_trunc_ln42_loc_i_i_channel),
    .if_dout(trunc_ln42_loc_i_i_channel_dout),
    .if_num_data_valid(trunc_ln42_loc_i_i_channel_num_data_valid),
    .if_fifo_cap(trunc_ln42_loc_i_i_channel_fifo_cap),
    .if_empty_n(trunc_ln42_loc_i_i_channel_empty_n),
    .if_read(readmem4_U0_ap_ready)
);

mem2stream_fifo_w32_d3840_A cacheBuff_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(readmem4_U0_cacheBuff_i_i_din),
    .if_full_n(cacheBuff_full_n),
    .if_write(readmem4_U0_cacheBuff_i_i_write),
    .if_dout(cacheBuff_dout),
    .if_num_data_valid(cacheBuff_num_data_valid),
    .if_fifo_cap(cacheBuff_fifo_cap),
    .if_empty_n(cacheBuff_empty_n),
    .if_read(dataflow_in_loop_VITIS_LOOP_38_1_1_Loop_VITIS_LOOP_43_2_proc5_U0_cacheBuff_read)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_channel_write_p_cast16_loc_i_i_channel <= 1'b0;
    end else begin
        if (((dataflow_in_loop_VITIS_LOOP_38_1_1_Block_newFuncRoot17_proc3_U0_ap_done & dataflow_in_loop_VITIS_LOOP_38_1_1_Block_newFuncRoot17_proc3_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_p_cast16_loc_i_i_channel <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_p_cast16_loc_i_i_channel <= ap_sync_channel_write_p_cast16_loc_i_i_channel;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_channel_write_trunc_ln42_loc_i_i_channel <= 1'b0;
    end else begin
        if (((dataflow_in_loop_VITIS_LOOP_38_1_1_Block_newFuncRoot17_proc3_U0_ap_done & dataflow_in_loop_VITIS_LOOP_38_1_1_Block_newFuncRoot17_proc3_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_trunc_ln42_loc_i_i_channel <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_trunc_ln42_loc_i_i_channel <= ap_sync_channel_write_trunc_ln42_loc_i_i_channel;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_dataflow_in_loop_VITIS_LOOP_38_1_1_Block_newFuncRoot17_proc3_U0_ap_ready <= 1'b0;
    end else begin
        if (((ap_sync_ready & ap_start) == 1'b1)) begin
            ap_sync_reg_dataflow_in_loop_VITIS_LOOP_38_1_1_Block_newFuncRoot17_proc3_U0_ap_ready <= 1'b0;
        end else begin
            ap_sync_reg_dataflow_in_loop_VITIS_LOOP_38_1_1_Block_newFuncRoot17_proc3_U0_ap_ready <= ap_sync_dataflow_in_loop_VITIS_LOOP_38_1_1_Block_newFuncRoot17_proc3_U0_ap_ready;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_readmem4_U0_ap_ready <= 1'b0;
    end else begin
        if (((ap_sync_ready & ap_start) == 1'b1)) begin
            ap_sync_reg_readmem4_U0_ap_ready <= 1'b0;
        end else begin
            ap_sync_reg_readmem4_U0_ap_ready <= ap_sync_readmem4_U0_ap_ready;
        end
    end
end

assign ap_channel_done_p_cast16_loc_i_i_channel = ((ap_sync_reg_channel_write_p_cast16_loc_i_i_channel ^ 1'b1) & dataflow_in_loop_VITIS_LOOP_38_1_1_Block_newFuncRoot17_proc3_U0_ap_done);

assign ap_channel_done_trunc_ln42_loc_i_i_channel = ((ap_sync_reg_channel_write_trunc_ln42_loc_i_i_channel ^ 1'b1) & dataflow_in_loop_VITIS_LOOP_38_1_1_Block_newFuncRoot17_proc3_U0_ap_done);

assign ap_done = dataflow_in_loop_VITIS_LOOP_38_1_1_Loop_VITIS_LOOP_43_2_proc5_U0_ap_done;

assign ap_idle = (readmem4_U0_ap_idle & (trunc_ln42_loc_i_i_channel_empty_n ^ 1'b1) & (p_cast16_loc_i_i_channel_empty_n ^ 1'b1) & dataflow_in_loop_VITIS_LOOP_38_1_1_Loop_VITIS_LOOP_43_2_proc5_U0_ap_idle & dataflow_in_loop_VITIS_LOOP_38_1_1_Block_newFuncRoot17_proc3_U0_ap_idle);

assign ap_ready = ap_sync_ready;

assign ap_sync_channel_write_p_cast16_loc_i_i_channel = ((p_cast16_loc_i_i_channel_full_n & ap_channel_done_p_cast16_loc_i_i_channel) | ap_sync_reg_channel_write_p_cast16_loc_i_i_channel);

assign ap_sync_channel_write_trunc_ln42_loc_i_i_channel = ((trunc_ln42_loc_i_i_channel_full_n & ap_channel_done_trunc_ln42_loc_i_i_channel) | ap_sync_reg_channel_write_trunc_ln42_loc_i_i_channel);

assign ap_sync_dataflow_in_loop_VITIS_LOOP_38_1_1_Block_newFuncRoot17_proc3_U0_ap_ready = (dataflow_in_loop_VITIS_LOOP_38_1_1_Block_newFuncRoot17_proc3_U0_ap_ready | ap_sync_reg_dataflow_in_loop_VITIS_LOOP_38_1_1_Block_newFuncRoot17_proc3_U0_ap_ready);

assign ap_sync_readmem4_U0_ap_ready = (readmem4_U0_ap_ready | ap_sync_reg_readmem4_U0_ap_ready);

assign ap_sync_ready = (ap_sync_readmem4_U0_ap_ready & ap_sync_dataflow_in_loop_VITIS_LOOP_38_1_1_Block_newFuncRoot17_proc3_U0_ap_ready);

assign baseAddr_address0 = dataflow_in_loop_VITIS_LOOP_38_1_1_Block_newFuncRoot17_proc3_U0_baseAddr_address0;

assign baseAddr_ce0 = dataflow_in_loop_VITIS_LOOP_38_1_1_Block_newFuncRoot17_proc3_U0_baseAddr_ce0;

assign baseAddr_d0 = 32'd0;

assign baseAddr_we0 = 1'b0;

assign dataflow_in_loop_VITIS_LOOP_38_1_1_Block_newFuncRoot17_proc3_U0_ap_continue = (ap_sync_channel_write_trunc_ln42_loc_i_i_channel & ap_sync_channel_write_p_cast16_loc_i_i_channel);

assign dataflow_in_loop_VITIS_LOOP_38_1_1_Block_newFuncRoot17_proc3_U0_ap_start = ((ap_sync_reg_dataflow_in_loop_VITIS_LOOP_38_1_1_Block_newFuncRoot17_proc3_U0_ap_ready ^ 1'b1) & ap_start);

assign dataflow_in_loop_VITIS_LOOP_38_1_1_Loop_VITIS_LOOP_43_2_proc5_U0_ap_continue = ap_continue;

assign dataflow_in_loop_VITIS_LOOP_38_1_1_Loop_VITIS_LOOP_43_2_proc5_U0_ap_start = p_cast16_loc_i_i_channel_empty_n;

assign img_data_din = dataflow_in_loop_VITIS_LOOP_38_1_1_Loop_VITIS_LOOP_43_2_proc5_U0_img_data_din;

assign img_data_write = dataflow_in_loop_VITIS_LOOP_38_1_1_Loop_VITIS_LOOP_43_2_proc5_U0_img_data_write;

assign m_axi_gmem_ARADDR = readmem4_U0_m_axi_gmem_ARADDR;

assign m_axi_gmem_ARBURST = readmem4_U0_m_axi_gmem_ARBURST;

assign m_axi_gmem_ARCACHE = readmem4_U0_m_axi_gmem_ARCACHE;

assign m_axi_gmem_ARID = readmem4_U0_m_axi_gmem_ARID;

assign m_axi_gmem_ARLEN = readmem4_U0_m_axi_gmem_ARLEN;

assign m_axi_gmem_ARLOCK = readmem4_U0_m_axi_gmem_ARLOCK;

assign m_axi_gmem_ARPROT = readmem4_U0_m_axi_gmem_ARPROT;

assign m_axi_gmem_ARQOS = readmem4_U0_m_axi_gmem_ARQOS;

assign m_axi_gmem_ARREGION = readmem4_U0_m_axi_gmem_ARREGION;

assign m_axi_gmem_ARSIZE = readmem4_U0_m_axi_gmem_ARSIZE;

assign m_axi_gmem_ARUSER = readmem4_U0_m_axi_gmem_ARUSER;

assign m_axi_gmem_ARVALID = readmem4_U0_m_axi_gmem_ARVALID;

assign m_axi_gmem_AWADDR = 64'd0;

assign m_axi_gmem_AWBURST = 2'd0;

assign m_axi_gmem_AWCACHE = 4'd0;

assign m_axi_gmem_AWID = 1'd0;

assign m_axi_gmem_AWLEN = 32'd0;

assign m_axi_gmem_AWLOCK = 2'd0;

assign m_axi_gmem_AWPROT = 3'd0;

assign m_axi_gmem_AWQOS = 4'd0;

assign m_axi_gmem_AWREGION = 4'd0;

assign m_axi_gmem_AWSIZE = 3'd0;

assign m_axi_gmem_AWUSER = 1'd0;

assign m_axi_gmem_AWVALID = 1'b0;

assign m_axi_gmem_BREADY = 1'b0;

assign m_axi_gmem_RREADY = readmem4_U0_m_axi_gmem_RREADY;

assign m_axi_gmem_WDATA = 32'd0;

assign m_axi_gmem_WID = 1'd0;

assign m_axi_gmem_WLAST = 1'b0;

assign m_axi_gmem_WSTRB = 4'd0;

assign m_axi_gmem_WUSER = 1'd0;

assign m_axi_gmem_WVALID = 1'b0;

assign readmem4_U0_ap_continue = 1'b1;

assign readmem4_U0_ap_start = (trunc_ln42_loc_i_i_channel_empty_n & (ap_sync_reg_readmem4_U0_ap_ready ^ 1'b1) & ap_start);

endmodule //mem2stream_dataflow_in_loop_VITIS_LOOP_38_1_1
