// ==============================================================
// Generated by Vitis HLS v2023.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module edge_detector_thresholding_1080_1920_s (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        sobelImg_data_dout,
        sobelImg_data_num_data_valid,
        sobelImg_data_fifo_cap,
        sobelImg_data_empty_n,
        sobelImg_data_read,
        thresholdImg_data_din,
        thresholdImg_data_num_data_valid,
        thresholdImg_data_fifo_cap,
        thresholdImg_data_full_n,
        thresholdImg_data_write,
        p_read
);

parameter    ap_ST_fsm_state1 = 3'd1;
parameter    ap_ST_fsm_state2 = 3'd2;
parameter    ap_ST_fsm_state3 = 3'd4;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [7:0] sobelImg_data_dout;
input  [1:0] sobelImg_data_num_data_valid;
input  [1:0] sobelImg_data_fifo_cap;
input   sobelImg_data_empty_n;
output   sobelImg_data_read;
output  [7:0] thresholdImg_data_din;
input  [1:0] thresholdImg_data_num_data_valid;
input  [1:0] thresholdImg_data_fifo_cap;
input   thresholdImg_data_full_n;
output   thresholdImg_data_write;
input  [7:0] p_read;

reg ap_done;
reg ap_idle;
reg start_write;
reg sobelImg_data_read;
reg[7:0] thresholdImg_data_din;
reg thresholdImg_data_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
reg    ap_block_state1;
wire   [0:0] icmp_ln21_fu_49_p2;
reg   [0:0] icmp_ln21_reg_60;
wire    ap_CS_fsm_state2;
wire    grp_thresholding_1080_1920_Pipeline_VITIS_LOOP_35_3_VITIS_LOOP_37_4_fu_32_ap_start;
wire    grp_thresholding_1080_1920_Pipeline_VITIS_LOOP_35_3_VITIS_LOOP_37_4_fu_32_ap_done;
wire    grp_thresholding_1080_1920_Pipeline_VITIS_LOOP_35_3_VITIS_LOOP_37_4_fu_32_ap_idle;
wire    grp_thresholding_1080_1920_Pipeline_VITIS_LOOP_35_3_VITIS_LOOP_37_4_fu_32_ap_ready;
wire    grp_thresholding_1080_1920_Pipeline_VITIS_LOOP_35_3_VITIS_LOOP_37_4_fu_32_sobelImg_data_read;
wire   [7:0] grp_thresholding_1080_1920_Pipeline_VITIS_LOOP_35_3_VITIS_LOOP_37_4_fu_32_thresholdImg_data_din;
wire    grp_thresholding_1080_1920_Pipeline_VITIS_LOOP_35_3_VITIS_LOOP_37_4_fu_32_thresholdImg_data_write;
wire    grp_thresholding_1080_1920_Pipeline_VITIS_LOOP_23_1_VITIS_LOOP_25_2_fu_41_ap_start;
wire    grp_thresholding_1080_1920_Pipeline_VITIS_LOOP_23_1_VITIS_LOOP_25_2_fu_41_ap_done;
wire    grp_thresholding_1080_1920_Pipeline_VITIS_LOOP_23_1_VITIS_LOOP_25_2_fu_41_ap_idle;
wire    grp_thresholding_1080_1920_Pipeline_VITIS_LOOP_23_1_VITIS_LOOP_25_2_fu_41_ap_ready;
wire    grp_thresholding_1080_1920_Pipeline_VITIS_LOOP_23_1_VITIS_LOOP_25_2_fu_41_sobelImg_data_read;
wire   [7:0] grp_thresholding_1080_1920_Pipeline_VITIS_LOOP_23_1_VITIS_LOOP_25_2_fu_41_thresholdImg_data_din;
wire    grp_thresholding_1080_1920_Pipeline_VITIS_LOOP_23_1_VITIS_LOOP_25_2_fu_41_thresholdImg_data_write;
reg    grp_thresholding_1080_1920_Pipeline_VITIS_LOOP_35_3_VITIS_LOOP_37_4_fu_32_ap_start_reg;
wire    ap_CS_fsm_state3;
reg    grp_thresholding_1080_1920_Pipeline_VITIS_LOOP_23_1_VITIS_LOOP_25_2_fu_41_ap_start_reg;
reg    ap_block_state3_on_subcall_done;
reg   [2:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 3'd1;
#0 grp_thresholding_1080_1920_Pipeline_VITIS_LOOP_35_3_VITIS_LOOP_37_4_fu_32_ap_start_reg = 1'b0;
#0 grp_thresholding_1080_1920_Pipeline_VITIS_LOOP_23_1_VITIS_LOOP_25_2_fu_41_ap_start_reg = 1'b0;
end

edge_detector_thresholding_1080_1920_Pipeline_VITIS_LOOP_35_3_VITIS_LOOP_37_4 grp_thresholding_1080_1920_Pipeline_VITIS_LOOP_35_3_VITIS_LOOP_37_4_fu_32(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_thresholding_1080_1920_Pipeline_VITIS_LOOP_35_3_VITIS_LOOP_37_4_fu_32_ap_start),
    .ap_done(grp_thresholding_1080_1920_Pipeline_VITIS_LOOP_35_3_VITIS_LOOP_37_4_fu_32_ap_done),
    .ap_idle(grp_thresholding_1080_1920_Pipeline_VITIS_LOOP_35_3_VITIS_LOOP_37_4_fu_32_ap_idle),
    .ap_ready(grp_thresholding_1080_1920_Pipeline_VITIS_LOOP_35_3_VITIS_LOOP_37_4_fu_32_ap_ready),
    .sobelImg_data_dout(sobelImg_data_dout),
    .sobelImg_data_num_data_valid(2'd0),
    .sobelImg_data_fifo_cap(2'd0),
    .sobelImg_data_empty_n(sobelImg_data_empty_n),
    .sobelImg_data_read(grp_thresholding_1080_1920_Pipeline_VITIS_LOOP_35_3_VITIS_LOOP_37_4_fu_32_sobelImg_data_read),
    .thresholdImg_data_din(grp_thresholding_1080_1920_Pipeline_VITIS_LOOP_35_3_VITIS_LOOP_37_4_fu_32_thresholdImg_data_din),
    .thresholdImg_data_num_data_valid(2'd0),
    .thresholdImg_data_fifo_cap(2'd0),
    .thresholdImg_data_full_n(thresholdImg_data_full_n),
    .thresholdImg_data_write(grp_thresholding_1080_1920_Pipeline_VITIS_LOOP_35_3_VITIS_LOOP_37_4_fu_32_thresholdImg_data_write),
    .p_read(p_read)
);

edge_detector_thresholding_1080_1920_Pipeline_VITIS_LOOP_23_1_VITIS_LOOP_25_2 grp_thresholding_1080_1920_Pipeline_VITIS_LOOP_23_1_VITIS_LOOP_25_2_fu_41(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_thresholding_1080_1920_Pipeline_VITIS_LOOP_23_1_VITIS_LOOP_25_2_fu_41_ap_start),
    .ap_done(grp_thresholding_1080_1920_Pipeline_VITIS_LOOP_23_1_VITIS_LOOP_25_2_fu_41_ap_done),
    .ap_idle(grp_thresholding_1080_1920_Pipeline_VITIS_LOOP_23_1_VITIS_LOOP_25_2_fu_41_ap_idle),
    .ap_ready(grp_thresholding_1080_1920_Pipeline_VITIS_LOOP_23_1_VITIS_LOOP_25_2_fu_41_ap_ready),
    .sobelImg_data_dout(sobelImg_data_dout),
    .sobelImg_data_num_data_valid(2'd0),
    .sobelImg_data_fifo_cap(2'd0),
    .sobelImg_data_empty_n(sobelImg_data_empty_n),
    .sobelImg_data_read(grp_thresholding_1080_1920_Pipeline_VITIS_LOOP_23_1_VITIS_LOOP_25_2_fu_41_sobelImg_data_read),
    .thresholdImg_data_din(grp_thresholding_1080_1920_Pipeline_VITIS_LOOP_23_1_VITIS_LOOP_25_2_fu_41_thresholdImg_data_din),
    .thresholdImg_data_num_data_valid(2'd0),
    .thresholdImg_data_fifo_cap(2'd0),
    .thresholdImg_data_full_n(thresholdImg_data_full_n),
    .thresholdImg_data_write(grp_thresholding_1080_1920_Pipeline_VITIS_LOOP_23_1_VITIS_LOOP_25_2_fu_41_thresholdImg_data_write)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_state3) & (1'b0 == ap_block_state3_on_subcall_done))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_thresholding_1080_1920_Pipeline_VITIS_LOOP_23_1_VITIS_LOOP_25_2_fu_41_ap_start_reg <= 1'b0;
    end else begin
        if (((icmp_ln21_fu_49_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
            grp_thresholding_1080_1920_Pipeline_VITIS_LOOP_23_1_VITIS_LOOP_25_2_fu_41_ap_start_reg <= 1'b1;
        end else if ((grp_thresholding_1080_1920_Pipeline_VITIS_LOOP_23_1_VITIS_LOOP_25_2_fu_41_ap_ready == 1'b1)) begin
            grp_thresholding_1080_1920_Pipeline_VITIS_LOOP_23_1_VITIS_LOOP_25_2_fu_41_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_thresholding_1080_1920_Pipeline_VITIS_LOOP_35_3_VITIS_LOOP_37_4_fu_32_ap_start_reg <= 1'b0;
    end else begin
        if (((icmp_ln21_fu_49_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
            grp_thresholding_1080_1920_Pipeline_VITIS_LOOP_35_3_VITIS_LOOP_37_4_fu_32_ap_start_reg <= 1'b1;
        end else if ((grp_thresholding_1080_1920_Pipeline_VITIS_LOOP_35_3_VITIS_LOOP_37_4_fu_32_ap_ready == 1'b1)) begin
            grp_thresholding_1080_1920_Pipeline_VITIS_LOOP_35_3_VITIS_LOOP_37_4_fu_32_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((real_start == 1'b1) & (internal_ap_ready == 1'b0))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        icmp_ln21_reg_60 <= icmp_ln21_fu_49_p2;
    end
end

always @ (*) begin
    if (((real_start == 1'b0) | (ap_done_reg == 1'b1))) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_block_state3_on_subcall_done)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) & (1'b0 == ap_block_state3_on_subcall_done))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((real_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) & (1'b0 == ap_block_state3_on_subcall_done))) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (start_full_n == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        if ((icmp_ln21_reg_60 == 1'd1)) begin
            sobelImg_data_read = grp_thresholding_1080_1920_Pipeline_VITIS_LOOP_23_1_VITIS_LOOP_25_2_fu_41_sobelImg_data_read;
        end else if ((icmp_ln21_reg_60 == 1'd0)) begin
            sobelImg_data_read = grp_thresholding_1080_1920_Pipeline_VITIS_LOOP_35_3_VITIS_LOOP_37_4_fu_32_sobelImg_data_read;
        end else begin
            sobelImg_data_read = 1'b0;
        end
    end else begin
        sobelImg_data_read = 1'b0;
    end
end

always @ (*) begin
    if (((real_start == 1'b1) & (start_once_reg == 1'b0))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        if ((icmp_ln21_reg_60 == 1'd1)) begin
            thresholdImg_data_din = grp_thresholding_1080_1920_Pipeline_VITIS_LOOP_23_1_VITIS_LOOP_25_2_fu_41_thresholdImg_data_din;
        end else if ((icmp_ln21_reg_60 == 1'd0)) begin
            thresholdImg_data_din = grp_thresholding_1080_1920_Pipeline_VITIS_LOOP_35_3_VITIS_LOOP_37_4_fu_32_thresholdImg_data_din;
        end else begin
            thresholdImg_data_din = grp_thresholding_1080_1920_Pipeline_VITIS_LOOP_23_1_VITIS_LOOP_25_2_fu_41_thresholdImg_data_din;
        end
    end else begin
        thresholdImg_data_din = grp_thresholding_1080_1920_Pipeline_VITIS_LOOP_23_1_VITIS_LOOP_25_2_fu_41_thresholdImg_data_din;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        if ((icmp_ln21_reg_60 == 1'd1)) begin
            thresholdImg_data_write = grp_thresholding_1080_1920_Pipeline_VITIS_LOOP_23_1_VITIS_LOOP_25_2_fu_41_thresholdImg_data_write;
        end else if ((icmp_ln21_reg_60 == 1'd0)) begin
            thresholdImg_data_write = grp_thresholding_1080_1920_Pipeline_VITIS_LOOP_35_3_VITIS_LOOP_37_4_fu_32_thresholdImg_data_write;
        end else begin
            thresholdImg_data_write = 1'b0;
        end
    end else begin
        thresholdImg_data_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if (((1'b1 == ap_CS_fsm_state3) & (1'b0 == ap_block_state3_on_subcall_done))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

always @ (*) begin
    ap_block_state1 = ((real_start == 1'b0) | (ap_done_reg == 1'b1));
end

always @ (*) begin
    ap_block_state3_on_subcall_done = (((grp_thresholding_1080_1920_Pipeline_VITIS_LOOP_23_1_VITIS_LOOP_25_2_fu_41_ap_done == 1'b0) & (icmp_ln21_reg_60 == 1'd1)) | ((grp_thresholding_1080_1920_Pipeline_VITIS_LOOP_35_3_VITIS_LOOP_37_4_fu_32_ap_done == 1'b0) & (icmp_ln21_reg_60 == 1'd0)));
end

assign ap_ready = internal_ap_ready;

assign grp_thresholding_1080_1920_Pipeline_VITIS_LOOP_23_1_VITIS_LOOP_25_2_fu_41_ap_start = grp_thresholding_1080_1920_Pipeline_VITIS_LOOP_23_1_VITIS_LOOP_25_2_fu_41_ap_start_reg;

assign grp_thresholding_1080_1920_Pipeline_VITIS_LOOP_35_3_VITIS_LOOP_37_4_fu_32_ap_start = grp_thresholding_1080_1920_Pipeline_VITIS_LOOP_35_3_VITIS_LOOP_37_4_fu_32_ap_start_reg;

assign icmp_ln21_fu_49_p2 = ((p_read == 8'd0) ? 1'b1 : 1'b0);

assign start_out = real_start;

endmodule //edge_detector_thresholding_1080_1920_s
